INSERT INTO packages (
  title, slug, description, category,
  destination, destination_slug,
  price, original_price, duration, nights, days,
  location, image_url, gallery,
  itinerary, highlights, inclusions, exclusions, know_before, route,
  rating, review_count
) VALUES
(
  'Shimla Weekend Getaway',
  'shimla-weekend-getaway-3d',
  'A relaxing short escape to the Queen of Hills, perfect for families and couples. Enjoy pleasant weather, colonial architecture, and local shopping.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  12999, 15999, '2 Nights / 3 Days', 2, 3,
  'Shimla, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Arrival and Mall Road Leisure","description":"Arrive in Shimla and check into your hotel. Spend the evening strolling down the famous Mall Road and Ridge, taking in the panoramic views."},
    {"day":2,"title":"Kufri Excursion and Local Sights","description":"Drive to Kufri to enjoy snow points and nature parks. Return to Shimla to visit Jakhu Temple and Christ Church."},
    {"day":3,"title":"Departure","description":"After breakfast, check out and drive back, carrying beautiful memories of the hills."}
  ]'::jsonb,
  to_jsonb(ARRAY['Mall Road Walk','Jakhu Temple','Christ Church','Kufri Snow Point','Himachali Cuisine']),
  to_jsonb(ARRAY['2 Nights Accommodation','Breakfast and Dinner','Private Sedan Transfer','Sightseeing as per itinerary']),
  to_jsonb(ARRAY['Lunch','Entry tickets to amusement parks','Personal expenses','Travel insurance']),
  to_jsonb(ARRAY['Carry warm clothing even in summer','Wear comfortable walking shoes','Keep an umbrella handy']),
  to_jsonb(ARRAY['Delhi','Shimla','Kufri','Delhi']),
  4.6, 312
),
(
  'Manali Adventure Retreat',
  'manali-adventure-retreat-4d',
  'Experience the thrill of the Himalayas in the bustling resort town of Manali. Ideal for adventure enthusiasts and thrill-seekers.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  18999, 23999, '3 Nights / 4 Days', 3, 4,
  'Manali, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Volvo Bus from Delhi to Manali","description":"Board your comfortable overnight Volvo bus from Delhi. Enjoy the scenic transition from plains to mountains."},
    {"day":2,"title":"Manali Local Sightseeing","description":"Check in, freshen up, and visit Hadimba Temple, Vashisht Hot Springs, and the Tibetan Monastery. Evening free at Mall Road."},
    {"day":3,"title":"Solang Valley Thrills","description":"Head to Solang Valley for adventurous activities like paragliding, zorbing, and cable car rides. Return to Manali for an overnight stay."},
    {"day":4,"title":"Departure","description":"Morning at leisure. Check out and board your evening Volvo bus back to Delhi."}
  ]'::jsonb,
  to_jsonb(ARRAY['Hadimba Temple','Solang Valley Paragliding','Vashisht Village','Mall Road','Tibetan Monastery']),
  to_jsonb(ARRAY['Overnight Volvo tickets','3 Nights Hotel Stay','Breakfast and Dinner','Solang Valley Day Trip','All transfers']),
  to_jsonb(ARRAY['Adventure sports fees','ATV rides','Lunch','Any personal expenses']),
  to_jsonb(ARRAY['Adventure sports subject to weather conditions','Carry windproof jackets','Book activities in advance']),
  to_jsonb(ARRAY['Delhi','Manali','Solang Valley','Delhi']),
  4.8, 455
),
(
  'Spiti Valley Expedition',
  'spiti-valley-expedition-9d',
  'A challenging and spectacular road trip through the cold desert of Spiti. Designed for extreme nature lovers and photography enthusiasts.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  45000, 56000, '8 Nights / 9 Days', 8, 9,
  'Kaza, Spiti Valley, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Shimla to Sangla","description":"Drive from Shimla to Sangla Valley via Kinnaur. Witness the stunning views of the Baspa River and traditional wooden houses."},
    {"day":2,"title":"Sangla to Chitkul and Kalpa","description":"Visit Chitkul, the last village on the old Indo-Tibet border. Proceed to Kalpa to view the majestic Kinner Kailash peaks."},
    {"day":3,"title":"Kalpa to Nako and Tabo","description":"Cross the Khab confluence of Spiti and Satluj rivers. Visit Nako Lake and the ancient Tabo Monastery."},
    {"day":4,"title":"Tabo to Kaza via Dhankar","description":"Explore the thousand-year-old Tabo caves. Visit Dhankar Monastery perched precariously on a cliff before heading to Kaza."},
    {"day":5,"title":"Key Monastery and Kibber Village","description":"Drive to the iconic Key Gompa. Continue to the high-altitude villages of Kibber, Chicham Bridge, and Gette."},
    {"day":6,"title":"Hikkim, Komik, and Langza","description":"Visit the world''s highest post office in Hikkim. See the highest village connected by road in Komik, and the giant Buddha statue in Langza."},
    {"day":7,"title":"Kaza to Chandratal Lake","description":"Travel over the formidable Kunzum Pass to reach the crescent-shaped Chandratal Lake. Camp under the starry skies."},
    {"day":8,"title":"Chandratal to Manali","description":"Drive past the rugged terrain of Batal and Rohtang Pass to arrive in Manali. Rest and relax at the hotel."},
    {"day":9,"title":"Departure from Manali","description":"After a hearty breakfast, check out and conclude your epic trans-Himalayan journey."}
  ]'::jsonb,
  to_jsonb(ARRAY['Kinner Kailash View','Ancient Tabo Monastery','Key Monastery','World''s Highest Post Office','Chandratal Lake Camping']),
  to_jsonb(ARRAY['8 Nights Accommodation in camps/hotels','MAP meal plan (Breakfast & Dinner)','Experienced expedition guide','Backup vehicle for safety']),
  to_jsonb(ARRAY['Inner Line Permits','Oxygen cylinders','Heavy winter gear','Lunch','Personal expenses']),
  to_jsonb(ARRAY['High risk of AMS (Acute Mountain Sickness)','Hydrate constantly','Carry cash as ATMs are rare in Spiti']),
  to_jsonb(ARRAY['Shimla','Sangla','Kalpa','Kaza','Chandratal','Manali']),
  4.9, 185
),
(
  'Dharamshala & Dalhousie Romance',
  'dharamshala-dalhousie-romance-5d',
  'A serene, picturesque honeymoon trip covering the twin gems of Himachal. Pine forests, snow-capped peaks, and Tibetan culture await.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  26999, 33999, '4 Nights / 5 Days', 4, 5,
  'Dharamshala, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Arrival in Dharamshala","description":"Arrive in Dharamshala. Check in to your resort. Spend the evening relaxing and enjoying the peaceful atmosphere."},
    {"day":2,"title":"McLeod Ganj Exploration","description":"Visit the Dalai Lama Temple, Bhagsu Nag Waterfall, and St. John in the Wilderness Church. Explore the bustling McLeod Ganj market."},
    {"day":3,"title":"Transfer to Dalhousie","description":"Drive to Dalhousie. Check in and head out for a romantic walk at Subhash Baoli and Gandhi Chowk."},
    {"day":4,"title":"Khajjiar Excursion","description":"Day trip to Khajjiar, known as the ''Mini Switzerland of India''. Enjoy zorbing and the sweeping green meadows."},
    {"day":5,"title":"Departure","description":"After breakfast, check out and transfer to Pathankot or Gaggal for your onward journey."}
  ]'::jsonb,
  to_jsonb(ARRAY['Dalai Lama Temple','Bhagsu Nag Waterfall','Mini Switzerland Khajjiar','Subhash Baoli','Panchpula']),
  to_jsonb(ARRAY['4 Nights Premium Accommodation','Breakfast and Dinner','Private AC Cab Transportation','Khajjiar sightseeing trip']),
  to_jsonb(ARRAY['Entry fee to monuments','Zorbing charges','Lunch','Travel insurance']),
  to_jsonb(ARRAY['Carry light woolens for evenings','Respect local monastery rules']),
  to_jsonb(ARRAY['Dharamshala','McLeod Ganj','Dalhousie','Khajjiar','Pathankot']),
  4.7, 298
),
(
  'Kinnaur and Sangla Valley Tour',
  'kinnaur-sangla-valley-7d',
  'Venture deep into the lesser-explored Kinnaur district. Rich in culture, apple orchards, and towering rugged mountains.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  29999, 36999, '6 Nights / 7 Days', 6, 7,
  'Sangla, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Shimla to Rampur to Reckong Peo","description":"Drive from Shimla traversing through the Satluj river valley. Reach Reckong Peo and get stunning glimpses of Kinner Kailash."},
    {"day":2,"title":"Move to Sangla Valley","description":"Descend into the picturesque Sangla Valley. Visit Kamru Fort and the ancient village temple."},
    {"day":3,"title":"Chitkul Day Excursion","description":"Drive to Chitkul, the last inhabited village near the Indo-Tibetan border. Walk by the gushing Baspa River."},
    {"day":4,"title":"Sangla to Kalpa","description":"Drive to Kalpa village. Enjoy surreal sunrise and sunset views over the Kinner Kailash range from your hotel room balcony."},
    {"day":5,"title":"Explore Roghi and Chini Villages","description":"Walk through the traditional villages of Roghi and Chini. Witness the local architecture and apple orchards."},
    {"day":6,"title":"Kalpa to Narkanda","description":"Drive back via Rampur to reach Narkanda. Enjoy a peaceful evening amidst apple and cherry orchards."},
    {"day":7,"title":"Narkanda to Shimla / Departure","description":"Morning visit to Hatu Peak. Check out and drive to Shimla/Chandigarh for onward departure."}
  ]'::jsonb,
  to_jsonb(ARRAY['Baspa River banks','Chitkul Village','Kinner Kailash Range','Kamru Fort','Hatu Peak']),
  to_jsonb(ARRAY['6 Nights Accommodations','All meals (Breakfast, Lunch, Dinner)','Private SUV transport','Guided village walking tours']),
  to_jsonb(ARRAY['Snacks and beverages','Tips and porterage','Personal travel insurance']),
  to_jsonb(ARRAY['Carry heavy woolens for Kalpa/Chitkul','Roads can be rough, prepare for motion sickness']),
  to_jsonb(ARRAY['Shimla','Sangla','Chitkul','Kalpa','Narkanda','Chandigarh']),
  4.5, 120
),
(
  'Kasauli & Chail Peaceful Weekend',
  'kasauli-chail-peaceful-weekend-3d',
  'A serene getaway in the Shivalik foothills. Ideal for escaping the urban chaos, featuring lush forests and colonial charm.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  11999, 14999, '2 Nights / 3 Days', 2, 3,
  'Kasauli, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Arrival in Kasauli","description":"Check in to your hotel in Kasauli. Spend the afternoon exploring the Gilbert Trail and Monkey Point with expansive views of the plains."},
    {"day":2,"title":"Excursion to Chail","description":"Drive to Chail. Visit the famous Chail Palace, the world''s highest cricket ground, and the Kali Ka Tibba temple."},
    {"day":3,"title":"Departure","description":"Enjoy a slow morning. Check out and proceed to your home destination."}
  ]'::jsonb,
  to_jsonb(ARRAY['Gilbert Nature Trail','Monkey Point','Chail Palace','Highest Cricket Ground','Kali Ka Tibba']),
  to_jsonb(ARRAY['2 Nights Hotel Stay','Breakfast and Dinner','Private Sedan Cab','Sightseeing as per itinerary']),
  to_jsonb(ARRAY['Lunch','Entry fees to Palace or monuments','Personal expenses']),
  to_jsonb(ARRAY['Wear comfortable shoes for hiking Gilbert Trail','Peaceful and quiet location, perfect for digital detox']),
  to_jsonb(ARRAY['Chandigarh','Kasauli','Chail','Chandigarh']),
  4.6, 215
),
(
  'Khajjiar & Chamba Heritage Tour',
  'khajjiar-chamba-heritage-4d',
  'Discover the rich historical tapestry of Chamba district paired with the mesmerizing green bowl of Khajjiar.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  15499, 18999, '3 Nights / 4 Days', 3, 4,
  'Chamba, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Arrival in Dalhousie & Transfer to Khajjiar","description":"Arrive at the base. Drive directly to Khajjiar. Check in to a forest-view resort and relax."},
    {"day":2,"title":"Khajjiar Meadows and Activities","description":"Spend the day enjoying the meadows of Khajjiar. Try zorbing, horse riding, and visit the Kalatop Wildlife Sanctuary nearby."},
    {"day":3,"title":"Chamba Sightseeing","description":"Take a day trip to Chamba town. Visit the Lakshmi Narayan Temple, Akhand Chandi Palace, and the Bhuri Singh Museum."},
    {"day":4,"title":"Departure","description":"After breakfast, check out and commence your departure journey."}
  ]'::jsonb,
  to_jsonb(ARRAY['Khajjiar Lake','Kalatop Sanctuary','Lakshmi Narayan Temple','Chamba Chaughan','Bhuri Singh Museum']),
  to_jsonb(ARRAY['3 Nights Accommodation','Breakfast and Dinner','Dedicated private transport','Chamba excursion']),
  to_jsonb(ARRAY['Museum entry fee','Guide charges','Lunch','Personal items']),
  to_jsonb(ARRAY['Carry cash as network can be patchy in remote areas','Do not litter the meadows']),
  to_jsonb(ARRAY['Pathankot','Khajjiar','Chamba','Pathankot']),
  4.5, 95
),
(
  'Kasol & Kheerganga Trekking Expedition',
  'kasol-kheerganga-trekking-expedition-5d',
  'Immerse yourself in the hippie culture of Parvati Valley while trekking through dense pine forests to natural hot springs.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  14999, 18999, '4 Nights / 5 Days', 4, 5,
  'Kasol, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Arrival in Kasol","description":"Arrive in Kasol. Check in at the riverside camps. Spend the day exploring the local cafes and Israeli culture."},
    {"day":2,"title":"Trek from Kasol to Barshaini and Reach Kheerganga","description":"Drive to Barshaini and begin your trek to Kheerganga. Pass through waterfalls and lush greenery. Camp overnight under the stars."},
    {"day":3,"title":"Dip in Hot Springs and Descend to Kasol","description":"Wake up to majestic mountain views and take a dip in the holy hot water springs. Trek back down to Kasol and check in to the hotel."},
    {"day":4,"title":"Chalal and Manikaran Gurudwara","description":"Short hike to Chalal village. Visit the Manikaran Gurudwara and hot springs. Spend the evening relaxing by the Parvati River."},
    {"day":5,"title":"Departure","description":"Check out and board your bus/cab back home."}
  ]'::jsonb,
  to_jsonb(ARRAY['Parvati River Views','Kheerganga Hot Springs','Barshaini Trek','Manikaran Sahib','Cafe Hopping in Kasol']),
  to_jsonb(ARRAY['2 Nights Kasol Stay','1 Night Kheerganga Camp Stay','1 Night Kasol Hotel Stay','Breakfast and Dinner','Trek Guide']),
  to_jsonb(ARRAY['Trekking gear','Sleeping bags if needed','Lunch','Personal expenses']),
  to_jsonb(ARRAY['Moderate level of fitness required for the trek','Carry sufficient water and energy bars','Respect local customs']),
  to_jsonb(ARRAY['Delhi','Kasol','Barshaini','Kheerganga','Delhi']),
  4.8, 385
),
(
  'Lahaul and Jispa Wilderness Tour',
  'lahaul-and-jispa-wilderness-tour-6d',
  'Cross the Atal Tunnel to explore the stark beauty of Lahaul Valley. A peaceful and less crowded alternative to full Ladakh circuits.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  27999, 34999, '5 Nights / 6 Days', 5, 6,
  'Jispa, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Manali to Sissu (Lahaul)","description":"Drive through the engineering marvel, the Atal Tunnel. Reach Sissu, surrounded by waterfalls and willow trees. Overnight in Sissu."},
    {"day":2,"title":"Explore Sissu and Keylong","description":"Visit the Sissu Waterfall, and travel to Keylong, the administrative headquarters of Lahaul. Explore the local monasteries."},
    {"day":3,"title":"Transfer to Jispa","description":"Drive further up to Jispa. Set on the banks of the Bhaga River, enjoy the serene, untouched natural environment."},
    {"day":4,"title":"Suraj Tal and Baralacha La Excursion","description":"Take a scenic drive towards the high-altitude Baralacha La pass. Witness the stunning, pristine high-altitude lake, Suraj Tal."},
    {"day":5,"title":"Jispa to Manali","description":"Drive back down to Manali. Spend the afternoon shopping for local Himachali knick-knacks and relax at a cafe."},
    {"day":6,"title":"Departure","description":"After breakfast, complete check-out formalities and depart."}
  ]'::jsonb,
  to_jsonb(ARRAY['Atal Tunnel Drive','Sissu Waterfall','Bhaga River banks','Suraj Tal Lake','Keylong Monastery']),
  to_jsonb(ARRAY['5 Nights Accommodations','Daily Breakfast and Dinner','Private SUV for the entire trip','Sightseeing as specified']),
  to_jsonb(ARRAY['Permits if required for interiors','Lunch','Personal items','Travel insurance']),
  to_jsonb(ARRAY['Temperatures drop significantly at night, dress accordingly','Carry valid ID proofs']),
  to_jsonb(ARRAY['Manali','Atal Tunnel','Sissu','Keylong','Jispa','Baralacha La','Manali']),
  4.6, 142
),
(
  'Tirthan Valley & Jibhi Nature Hideout',
  'tirthan-valley-jibhi-nature-hideout-4d',
  'Unwind in the untouched Tirthan Valley. Perfect for nature lovers, trout fishing, and slow-paced offbeat travel.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  16999, 21999, '3 Nights / 4 Days', 3, 4,
  'Jibhi, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Arrival in Jibhi","description":"Arrive at your riverside cottage in Jibhi. Relax by the pristine Tirthan River and take a short walk to the nearby waterfall."},
    {"day":2,"title":"Jalori Pass and Serolsar Lake Trek","description":"Drive to Jalori Pass. Hike through thick oak and deodar forests to the beautiful Serolsar Lake. Return to Jibhi for overnight stay."},
    {"day":3,"title":"Great Himalayan National Park & Trout Fishing","description":"Explore the fringes of the Great Himalayan National Park. Try your hand at trout fishing and enjoy authentic local pahadi cuisine."},
    {"day":4,"title":"Departure","description":"After a peaceful breakfast, check out and commence your return journey."}
  ]'::jsonb,
  to_jsonb(ARRAY['Jalori Pass Hike','Serolsar Lake','Jibhi Waterfall','Tirthan River Trout Fishing','GHNP Entry point']),
  to_jsonb(ARRAY['3 Nights Cottage Stay','Breakfast and Dinner','Private Cab Transportation','Jalori Pass drop and pickup']),
  to_jsonb(ARRAY['Trout fishing license fees','Trek guide','Lunch','Personal expenses']),
  to_jsonb(ARRAY['Jalori Pass road can be bumpy, prepare accordingly','Carry raincoats/umbrellas for mountain showers']),
  to_jsonb(ARRAY['Delhi','Jibhi','Jalori Pass','Delhi']),
  4.7, 274
),
(
  'Palampur Tea Gardens Retreat',
  'palampur-tea-gardens-retreat-5d',
  'Rejuvenate amidst the sprawling tea estates of Palampur. The valley features gushing streams and sweeping views of the Dhauladhar range.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  22499, 27999, '4 Nights / 5 Days', 4, 5,
  'Palampur, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Arrival in Palampur","description":"Arrive in Palampur and check into a heritage property nestled within tea plantations. Spend the day at leisure."},
    {"day":2,"title":"Tea Gardens & Saurabh Van Vihar","description":"Take a guided tour of the tea factories and gardens. Visit Saurabh Van Vihar and the Neugal Khad cafe for tea and snacks."},
    {"day":3,"title":"Baijnath Temple and Andretta Pottery","description":"Visit the ancient Shiva temple at Baijnath. Head to Andretta, an artist''s village, and try your hand at pottery making."},
    {"day":4,"title":"Dharamshala Day Excursion","description":"Take a day trip to explore the nearby sights of Dharamshala, including the HPCA Cricket Stadium and War Memorial."},
    {"day":5,"title":"Departure","description":"After breakfast, check out and start your departure journey."}
  ]'::jsonb,
  to_jsonb(ARRAY['Palampur Tea Gardens','Neugal Khad','Baijnath Temple','Andretta Artist Village','Dhauladhar Views']),
  to_jsonb(ARRAY['4 Nights Heritage Stay','Breakfast and Dinner','Private Car Transfer','Tea Garden Guided Walk']),
  to_jsonb(ARRAY['Andretta pottery workshop fee','Entry tickets','Lunch','Personal expenses']),
  to_jsonb(ARRAY['Ideal for a quiet, relaxing holiday','Local transport inside town is easily available']),
  to_jsonb(ARRAY['Pathankot','Palampur','Andretta','Dharamshala','Pathankot']),
  4.6, 190
),
(
  'McLeod Ganj Spiritual & Cultural Trail',
  'mcleod-ganj-spiritual-cultural-trail-4d',
  'Dive into the cultural and spiritual hub of Tibetan exiles. Great for meditation, momos, and mountain trekking.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  13999, 17499, '3 Nights / 4 Days', 3, 4,
  'McLeod Ganj, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Arrival and Monastery Walk","description":"Arrive in McLeod Ganj. Check in to your hotel and visit the Tsuglagkhang Complex (Dalai Lama Temple). Enjoy evening prayer vibes."},
    {"day":2,"title":"Trek to Triund","description":"Start an exciting trek to Triund Hill. Walk through lush deodar and oak forests. Camp overnight under the stars or return to the base."},
    {"day":3,"title":"Bhagsu and Norbulingka Institute","description":"Descend from Triund and visit the Bhagsu Nag temple and waterfall. Visit the Norbulingka Institute to see Tibetan arts and crafts."},
    {"day":4,"title":"Departure","description":"After breakfast, check out and begin your return journey."}
  ]'::jsonb,
  to_jsonb(ARRAY['Tsuglagkhang Temple','Triund Trek','Norbulingka Institute','Bhagsu Waterfall','Tibetan Food Tasting']),
  to_jsonb(ARRAY['3 Nights Accommodation','Breakfast and Dinner','Triund Trek Guide','Private transfers']),
  to_jsonb(ARRAY['Triund camping meals (if opting to stay overnight)','Lunch','Personal expenses']),
  to_jsonb(ARRAY['Triund trek requires moderate stamina','Do not litter on the trails']),
  to_jsonb(ARRAY['Delhi','McLeod Ganj','Triund','Delhi']),
  4.7, 345
),
(
  'Shimla to Manali Scenic Road Trip',
  'shimla-to-manali-scenic-road-trip-6d',
  'The quintessential Himachal road journey. Travel from the capital of Shimla up to the adventure capital of Manali, passing stunning river valleys.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  24999, 30999, '5 Nights / 6 Days', 5, 6,
  'Manali, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Arrival in Shimla","description":"Arrive in Shimla. Check into your hotel and enjoy a peaceful evening walk on the Ridge and Mall Road."},
    {"day":2,"title":"Shimla to Manali Drive","description":"Embark on a beautiful, winding road trip from Shimla to Manali. Pass through lush valleys, apple orchards, and the Pandoh Dam. Check in to Manali hotel."},
    {"day":3,"title":"Manali Local Sights","description":"Explore Hadimba Temple, Vashisht Village, Tibetan Monastery, and the Van Vihar nature park."},
    {"day":4,"title":"Solang Valley Excursion","description":"Enjoy a day full of adventure and snow activities at Solang Valley. Try paragliding or riding the ropeway."},
    {"day":5,"title":"Naggar Castle & Kullu Shawl Factory","description":"Drive to Naggar Castle to explore ancient pahari architecture and art. Visit a local shawl weaving center in Kullu."},
    {"day":6,"title":"Departure","description":"After breakfast, check out and proceed for your onward journey."}
  ]'::jsonb,
  to_jsonb(ARRAY['Pandoh Dam View','Naggar Castle','Solang Valley','Mall Road Shimla','Hadimba Temple']),
  to_jsonb(ARRAY['5 Nights Accommodations','Breakfast and Dinner','Private AC Car for the entire road trip','All inter-city transfers']),
  to_jsonb(ARRAY['Adventure sports fees','Ropeway tickets','Lunch','Travel insurance']),
  to_jsonb(ARRAY['Road trip takes about 7-8 hours, plan accordingly','Keep motion sickness medication handy']),
  to_jsonb(ARRAY['Shimla','Mandi','Pandoh Dam','Manali','Solang Valley','Kullu','Delhi']),
  4.8, 410
),
(
  'Grand Himachal Circuit',
  'grand-himachal-circuit-11d',
  'The ultimate comprehensive holiday across Himachal Pradesh. Experience everything from colonial towns to hippie valleys, and cold deserts.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  58999, 73999, '10 Nights / 11 Days', 10, 11,
  'Shimla, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Arrival in Shimla","description":"Arrive in Shimla. Check in and spend the evening relaxing on Mall Road."},
    {"day":2,"title":"Shimla to Kufri and Local Sightseeing","description":"Visit Jakhu Temple and take a day trip to Kufri snow point."},
    {"day":3,"title":"Shimla to Dharamshala","description":"Long drive from Shimla to Dharamshala. Check in and rest for the night."},
    {"day":4,"title":"Dharamshala Local Exploration","description":"Visit Dalai Lama Temple, Bhagsu Waterfall, and explore McLeod Ganj cafes."},
    {"day":5,"title":"Dharamshala to Dalhousie","description":"Scenic drive to Dalhousie. Evening walk around Gandhi Chowk."},
    {"day":6,"title":"Dalhousie to Khajjiar","description":"Day excursion to the mini-switzerland, Khajjiar, for zorbing and nature views."},
    {"day":7,"title":"Dalhousie to Manali","description":"Drive from Dalhousie to Manali via Mandi and Bilaspur. Overnight stay at Manali."},
    {"day":8,"title":"Manali Local Sights","description":"Visit Hadimba Temple, Vashisht Hot springs, and the local Tibetan Monastery."},
    {"day":9,"title":"Solang Valley Adventure","description":"Enjoy paragliding, zorbing, and cable-car rides at Solang Valley."},
    {"day":10,"title":"Manali to Sissu (Atal Tunnel) and Back","description":"Cross Atal Tunnel for a day trip to Sissu Waterfall in Lahaul Valley. Return to Manali."},
    {"day":11,"title":"Departure","description":"Morning at leisure. Check out and commence your departure journey to Delhi."}
  ]'::jsonb,
  to_jsonb(ARRAY['Shimla Ridge','Dalai Lama Temple','Khajjiar Meadows','Atal Tunnel Drive','Solang Valley']),
  to_jsonb(ARRAY['10 Nights Accommodations','Daily Breakfast and Dinner','Private Cab Transportation throughout the circuit','All toll and parking charges']),
  to_jsonb(ARRAY['Monuments entry tickets','Adventure activity costs','Lunch','Personal travel insurance']),
  to_jsonb(ARRAY['This is a long, extensive circuit, pace yourself appropriately','Pack layers as weather differs by region']),
  to_jsonb(ARRAY['Shimla','Dharamshala','Dalhousie','Khajjiar','Manali','Solang Valley','Lahaul','Delhi']),
  4.9, 582
),
(
  'Bir Billing Paragliding Expedition',
  'bir-billing-paragliding-expedition-3d',
  'Fly high in the sky at Bir Billing, the paragliding capital of the world. Perfect for adrenaline lovers and weekend flyers.',
  'domestic',
  'Himachal Pradesh', 'himachal-pradesh',
  10999, 13999, '2 Nights / 3 Days', 2, 3,
  'Bir, Himachal Pradesh',
  '/images/placeholder.svg', '[]'::jsonb,
  '[
    {"day":1,"title":"Arrival in Bir","description":"Arrive in Bir. Check into a backpacker hostel or cottage. Explore the Tibetan Colony, Chokling Monastery, and the landing site cafes."},
    {"day":2,"title":"Tandem Paragliding at Billing","description":"Drive to Billing (the take-off site). Fly tandem with a pilot over the Dhauladhar ranges and land at Bir (the landing site). Spend the evening reviewing photos."},
    {"day":3,"title":"Departure","description":"After breakfast, check out and depart for your onward destination."}
  ]'::jsonb,
  to_jsonb(ARRAY['Billing Take-off Site','Bir Landing Site','Chokling Monastery','Cafe Arto','Dhauladhar Views']),
  to_jsonb(ARRAY['2 Nights Stay','Breakfast and Dinner','Tandem Paragliding Flight (with GoPro video)','Local transfers in Bir']),
  to_jsonb(ARRAY['Lunch','Any extra paragliding attempts','Personal expenses']),
  to_jsonb(ARRAY['Paragliding is highly subject to clear weather and wind conditions','Listen to your pilot''s instructions carefully']),
  to_jsonb(ARRAY['Delhi','Bir','Billing','Delhi']),
  4.8, 311
);